// <auto-generated />
namespace MVC_Hims_V1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adddoctor151 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddoctor151));
        
        string IMigrationMetadata.Id
        {
            get { return "201709291848108_adddoctor151"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
