// <auto-generated />
namespace MVC_Hims_V1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adddoctorforce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddoctorforce));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281937418_adddoctor-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
